### PR TITLE
Update Xamarin.Forms Sample

### PR DESCRIPTION
**Pull request by brminnick**
This PR updates the Xamarin.Forms sample to use the latest NuGet Packages and enables `Nullable`

### CODE REVIEW

**Comment by Sergio0694** [comment]
Uh... What's going on with that 33k lines generated file? 😳
Is that... Normal? I mean, even for a generated file, that's a bit much 😅

**Comment by brminnick** [comment]
Ha! It's not abnormal, but yea it's just a compiler-generated file.

Let me see if some of the old tricks I used to use for these still work 👍

**Comment by brminnick** [comment]
Cool - I deleted the contents of the file and confirmed it still builds.

I also and added it to `.gitignore`.

Since the compiler auto-populates the file it's fine to just keep it as an empty class in the git repo 👍

**Comment by Sergio0694** [comment]
Now **that's** a gread PR diff if I've ever seen one 😄

image

**Review by Sergio0694 — APPROVED** [review]
LGTM, thank you! 😄

**Pull request closed without merging**
