### PR TITLE
Sample app updates

### PR DESCRIPTION
**Pull request by Sergio0694**
✅ Updated all NuGet packages
✅ Switched to `System.Text.Json` serialization
✅ Enabled nullability annotations in `.Core` project
✅ Enabled app trimming for .NET Native in UWP sample app

### CODE REVIEW

**Comment by virzak** [comment]
Looking to adapt this library, which is already annotated with Nullable. 
Migrating away from MvvmLight is resulting in:

```diff
-        private bool WindowDrop_CanExecute(DragEventArgs e)
+        private bool WindowDrop_CanExecute(DragEventArgs? e)
        {
+            _ = e ?? throw new ArgumentNullException(nameof(e));
```
everywhere where an argument is used.

Are there any future plans to introduce the API below?

```diff
    public sealed class AsyncRelayCommand<T> : ObservableObject, IAsyncRelayCommand<T>, IAsyncRelayCommand, IRelayCommand, ICommand, INotifyPropertyChanged, IRelayCommand<T>
    {
        public AsyncRelayCommand(Func<T?, Task> execute);
        public AsyncRelayCommand(Func<T?, CancellationToken, Task> cancelableExecute);
        public AsyncRelayCommand(Func<T?, Task> execute, Predicate<T?> canExecute);
        public AsyncRelayCommand(Func<T?, CancellationToken, Task> cancelableExecute, Predicate<T?> canExecute);
+        public AsyncRelayCommand(Func<T, Task> execute);
+        public AsyncRelayCommand(Func<T, CancellationToken, Task> cancelableExecute);
+        public AsyncRelayCommand(Func<T, Task> execute, Predicate<T> canExecute);
+        public AsyncRelayCommand(Func<T, CancellationToken, Task> cancelableExecute, Predicate<T> canExecute);
```

**Comment by Sergio0694** [comment]
Hi @virzak, adding those overloads would just not be possible, because they'd be conflicting.
As in, `T` and `T?` in this context is quite literally the same type, so those overloads are not actually overloads - they're the same.
The reason why the input arguments for these commands is nullable is for consistency with the actual [`ICommand`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.icommand) interface, which takes a nullable `object?` parameter for both the `Execute` and `CanExecute` methods. So we're just following suit with that 🙂

**Comment by Sergio0694** [comment]
@michael-hawker I've double checked everything's in place and did a force push to keep the history clean.
I've also switched to `CommunityToolkit.Mvvm` in https://github.com/CommunityToolkit/MVVM-Samples/pull/44/commits/6b3a4e965a1c5d1aeb8eee48e4b04f99d075e890 to make things simpler for #49 👍

**Comment by michael-hawker** [comment]
Thanks @Sergio0694 I'll try and check the XF sample with this PR today or Monday.

**Comment by michael-hawker** [comment]
Had to make some small tweaks, but the XF sample is working here too.

**Pull request merged**
